const config = {
  appID: 'IPP',
  REACT_APP_WEB3_STORAGE_API_TOKEN: process.env.REACT_APP_WEB3_STORAGE_API_TOKEN || "",
  REACT_APP_WEB3_STORAGE_IPNS_API_TOKEN: process.env.REACT_APP_WEB3_STORAGE_IPNS_API_TOKEN || "",
  LAST_SYNC_NUMBER: "IPP_LAST_SYNC_NUMBER",
  LAST_SYNC_RECORD: "LAST_SYNC_RECORD_",
  IPNS_DATA: "IPNS_DATA_",
  VERSION_LABEL: "VERSION",
  version: "#10",
  RSS_COUNT: 10
};

export default config;
